# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-18 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('stu_no', models.CharField(max_length=50)),
                ('profess', models.CharField(max_length=100)),
                ('collega', models.CharField(max_length=100)),
                ('className', models.CharField(max_length=100)),
            ],
        ),
    ]
